// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

type StubQueryBuilder = {
  select: (...args: any[]) => Promise<{ data: any; error: null }>;
  insert: (...args: any[]) => Promise<{ data: any; error: null }>;
  update: (...args: any[]) => Promise<{ data: any; error: null }>;
  delete: (...args: any[]) => Promise<{ data: any; error: null }>;
  eq: (...args: any[]) => StubQueryBuilder;
  order: (...args: any[]) => StubQueryBuilder;
  limit: (...args: any[]) => StubQueryBuilder;
  maybeSingle: () => Promise<{ data: any; error: null }>;
  single: () => Promise<{ data: any; error: null }>;
  in: (...args: any[]) => StubQueryBuilder;
  gte: (...args: any[]) => StubQueryBuilder;
  gt: (...args: any[]) => StubQueryBuilder;
  lte: (...args: any[]) => StubQueryBuilder;
  lt: (...args: any[]) => StubQueryBuilder;
  contains: (...args: any[]) => StubQueryBuilder;
  ilike: (...args: any[]) => StubQueryBuilder;
  or: (...args: any[]) => StubQueryBuilder;
  range: (...args: any[]) => StubQueryBuilder;
};

function createNoopQueryBuilder(): StubQueryBuilder {
  const builder = {
    select: async () => ({ data: [], error: null }),
    insert: async () => ({ data: null, error: null }),
    update: async () => ({ data: null, error: null }),
    delete: async () => ({ data: null, error: null }),
    eq: () => builder,
    order: () => builder,
    limit: () => builder,
    maybeSingle: async () => ({ data: null, error: null }),
    single: async () => ({ data: null, error: null }),
    in: () => builder,
    gte: () => builder,
    gt: () => builder,
    lte: () => builder,
    lt: () => builder,
    contains: () => builder,
    ilike: () => builder,
    or: () => builder,
    range: () => builder,
  };

  return builder as StubQueryBuilder;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR and build-time injection.
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    import.meta.env.SUPABASE_URL ||
    process.env.VITE_SUPABASE_URL ||
    process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    import.meta.env.SUPABASE_PUBLISHABLE_KEY ||
    process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn('[Supabase] Missing configuration. Falling back to a no-op client so the site can render without crashing.');

    return {
      auth: {
        onAuthStateChange: () => ({
          data: {
            subscription: {
              unsubscribe() {},
            },
          },
          error: null,
        }),
        getSession: async () => ({ data: { session: null }, error: null }),
        signOut: async () => ({ error: null }),
      },
      from: () => createNoopQueryBuilder(),
      rpc: async () => ({ data: null, error: null }),
      functions: {
        invoke: async () => ({ data: null, error: null }),
      },
    } as unknown as ReturnType<typeof createClient<Database>>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

